services:
  mongo:
    image: mongo:7.0
    container_name: disney-cruise-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cruise_search
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
