spring.application.name=payment-service
server.port=8083
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:payment_service}
spring.data.mongodb.auto-index-creation=true
app.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.consumer-group-id=payment-service
app.kafka.consumer-auto-offset-reset=earliest
app.kafka.reservation-created-topic=reservation-created
app.kafka.reservation-created-schema=avro/reservation-created-event.avsc
