spring.application.name=payment-service
server.port=8083
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:payment_service}
spring.data.mongodb.auto-index-creation=true
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationId:-}]
app.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.consumer.group-id=payment-service
app.kafka.consumer.auto-offset-reset=earliest
app.kafka.topics.reservation-created=reservation-created
app.kafka.schemas.reservation-created=avro/reservation-created-event.avsc
