spring.application.name=payment-service
server.port=8083
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/payment_service}
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info,metrics
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationId:-}]
