spring.application.name=reservation-service
server.port=8085
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:reservation_service}
spring.data.mongodb.auto-index-creation=true
app.clients.cruise-search.base-url=${CRUISE_SEARCH_BASE_URL:http://localhost:8081}
app.clients.cruise-search.bearer-token=${CRUISE_SEARCH_BEARER_TOKEN:}
app.clients.cruise-search.timeout=2s
management.endpoints.web.exposure.include=health,info,metrics
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationId:-}]
app.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topics.reservation-created=reservation-created
